### ISSUE TITLE
Voteup plug-in new feature request

### ISSUE THREAD

**Issue by BillZhucn** [Polar-Pumpkin/Shoal#1]
希望可以在config.yml中更改Autocast可使用指令列表的模式（blacklist或是whitelist）。感谢w qwq

**Comment by Polar-Pumpkin** [comment]
![](https://i.loli.net/2020/02/28/5tSJDybTX3fmvpL.jpg)

哇，居然有issue，居然有人在用VoteUp，我要感动死了。

马上马上

**Comment by Polar-Pumpkin** [comment]
![](https://i.loli.net/2020/02/28/RrVwhlNnmyaGqCj.jpg)

想问个事，VoteUp 真的能用嘛？你在使用过程中有没有遇到问题之类的

**Comment by BillZhucn** [comment]
刚刚才开始用XD，感觉用起来还不错，如果没问题应该可以说1.15.2是可以使用的。
看起来应该没啥bug（？）

**Comment by BillZhucn** [comment]
高版本的投票插件，还是GUI投票真的太棒了））
爱您w（づ￣3￣）づ╭❤～

**Comment by Polar-Pumpkin** [comment]
好啦，已经更新了。(VoteUp v1.4.1-R)
如果遇到其他问题记得反馈我噢，我会尽力解决的。

**Comment by BillZhucn** [comment]
我也更新上了XD 
小声在说一个feature））
可以看到正在进行的投票剩余时间））
我可以再开个issue（这样你就是有两个issue的人啦！）

**Comment by Polar-Pumpkin** [comment]
![](https://i.loli.net/2020/02/28/l9hjwxnOWQzeNXE.jpg)
好
并且我需要关于这个问题的更多信息

**Comment by BillZhucn** [comment]
不，这是new feature request hhhhhhh（感觉就像在定制插件）
太麻烦你了！！！！！！！！！！！！！！！！！！！！

**Comment by Polar-Pumpkin** [comment]
那好，0w0，我会想想实现方式的。
还有就是对于 Autocast 的更新，现在只会判断命令头，而不会扫描参数。
（在更改之前会尝试判断每个参数是否属于屏蔽关键词
所以如果使用黑名单的话要小心套娃命令，
比如**sudo op的ID kill 其他玩家ID**之类的命令
当然也许你是为了使用白名单功能 =w=

**Comment by BillZhucn** [comment]
对，我就是怕投票op这样，因为我看到实现方式是用后台执行指令。这样很多比较危险的指令就可能会被投票执行。所以我就来request whitelist的功能，这样就可以直接给希望玩家用的指令了√
爱你www
owo！！！！

**Comment by BillZhucn** [comment]
```
[17:40:26 ERROR]: Could not pass event PlayerJoinEvent to VoteUp v1.4.1-RELEASE
java.lang.ArrayIndexOutOfBoundsException: 0
        at net.shoal.sir.voteup.config.CacheManager.report(CacheManager.java:84) ~[?:?]
        at net.shoal.sir.voteup.listener.PlayerJoinListener.onJoin(PlayerJoinListener.java:16) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor92.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-121]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-121]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-121]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-121]
        at net.minecraft.server.v1_15_R1.PlayerList.a(PlayerList.java:192) ~[patched_1.15.2.jar:git-Paper-121]
        at net.minecraft.server.v1_15_R1.LoginListener.c(LoginListener.java:174) ~[patched_1.15.2.jar:git-Paper-121]
        at net.minecraft.server.v1_15_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.15.2.jar:git-Paper-121]
        at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:256) ~[patched_1.15.2.jar:git-Paper-121]
        at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.15.2.jar:git-Paper-121]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1269) ~[patched_1.15.2.jar:git-Paper-121]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-121]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-121]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-121]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
```

这个是不是不兼容1.15.2的体现））

**Comment by BillZhucn** [comment]
```
> version
[19:04:08 INFO]: This server is running Paper version git-Paper-121 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[19:04:08 INFO]: Checking version, please wait...
[19:04:09 INFO]: Previous version: git-Paper-120 (MC: 1.15.2)
[19:04:09 INFO]: You are running the latest version
> plugins
[19:04:10 INFO]: Plugins (29): AdvancedCleaner, BetterBees, CleanMotD*, CoreProtect, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, FarmProtect*, FastChunkPregenerator, HsRails*, IllegalStack, LuckPerms, MarriageMaster, Minecraft_QQ*, NotBoom*, PlaceholderAPI, Plan, PluginManager*, ProtocolLib, SAML, SimpleBackup*, SolidTraction, TAB, Tamablefoxes, TitleManager, Vault, VoteUp
```

**Comment by Polar-Pumpkin** [comment]
不是，是一个小问题，我现在在上课qwq，晚点修。
反馈问题你应该开一个新的issue嘛，感觉这要变成私有聊天串了 XD

**Comment by BillZhucn** [comment]
我一边上课一边看服务器后台摸鱼XD
以及雷狗子**好评**
Github issue ×
Gayhub chat √

**Comment by Polar-Pumpkin** [comment]
能提供更多错误发生的信息吗，每次玩家进入都会报错吗

**Comment by BillZhucn** [comment]
对，每次玩家进入都会报错

**Comment by Polar-Pumpkin** [comment]
我先放个鸽子🕊在这里，明天起来修awa.

**Comment by BillZhucn** [comment]
那我抓鸽子恰

**Comment by Polar-Pumpkin** [comment]
可能需要更多信息，能贴一下你的cache.yml嘛

**Comment by BillZhucn** [comment]
我要不要再开个issue XD cache.yml吗，
```
VOTE_VOTED:
  0wbillw0:
    '1':
      0wbillw0: 1582870647823
      Xiao_Rui: 1582870654592
      Kelikaoku: 1582870658365
      Reg: 1582870680600
    '2':
      0wbillw0: 1582875580787
      Furry__Caps: 1582875589239
      wolf_shenyi: 1582875610567
```

**Comment by Polar-Pumpkin** [comment]
就这样也没事，我习惯了 XD
大概知道问题在哪了，就快修好了

**Comment by Polar-Pumpkin** [comment]
发了一个更新，但是仍然可能存在问题。
我在撰写更新日志的时候想到了该解决方案的一个问题，如果你的玩家中存在ID以下划线结尾的玩家，那么可能该玩家相关的投票数据等会出现无法加载(具体为无法识别该玩家为投票发起人或其他)的情况。

**Comment by BillZhucn** [comment]
现在好像权限节点有点问题。如果玩家有Voteup.admin他们才能在autocast里面添加指令，不然会显示权限验证失败

**Comment by BillZhucn** [comment]
还有就是投票之后显示会刷屏
![无标题](https://user-images.githubusercontent.com/53694134/75750963-4d19c700-5d60-11ea-81c1-3422398884d4.png)
）

**Comment by Polar-Pumpkin** [comment]
在尝试创建投票的时候吗（显示权限验证失败）

**Comment by BillZhucn** [comment]
> 在尝试创建投票的时候吗（显示权限验证失败）

不是，是在添加autocast文本的时候显示权限验证失败

**Comment by Polar-Pumpkin** [comment]
找到问题了，是投票ID格式更改的后遗症。
- - -
我现在看看刷屏问题
- 刷屏只有你能看到吗？
- 是投票后马上看到？
- 还是投票-下线-上线后看到？

**Comment by BillZhucn** [comment]
是投完票就能看见。只有投票的人可以看见

**Comment by BillZhucn** [comment]
之前似乎没这毛病来着）捣鼓了一下权限组出来的。你知道现在总共有哪些权限组吗？

**Comment by Polar-Pumpkin** [comment]
> 之前似乎没这毛病来着）捣鼓了一下权限组出来的。你知道现在总共有哪些权限组吗？
- - -
是指权限组插件，还是VoteUp的所有权限节点

**Comment by BillZhucn** [comment]
> > 之前似乎没这毛病来着）捣鼓了一下权限组出来的。你知道现在总共有哪些权限组吗？
> 
> 是指权限组插件，还是VoteUp的所有权限节点

那肯定是作者大人写的VoteUp啦）

**Comment by Polar-Pumpkin** [comment]
你大概可以在[这里](https://github.com/Polar-Pumpkin/Shoal/blob/master/src/main/java/net/shoal/sir/voteup/enums/VoteUpPerm.java)看到所有的权限节点，或者是[这里](https://github.com/Polar-Pumpkin/Shoal/blob/master/src/main/resources/plugin.yml)
- - -
有些权限节点可能没有用上啥的... 事实上现在VoteUp的代码挺乱的，比起我现在写的别的项目qwq

**Comment by Polar-Pumpkin** [comment]
我大概发现了刷屏的原因，你是不是给玩家们`VoteUp.notice`权限了，或者是包含此权限的更高级的权限？

**Comment by BillZhucn** [comment]
给了voteup.admin，因为不给就没法用autocast）

**Comment by Polar-Pumpkin** [comment]
那大概就是因为`VoteUp.admin`包含`VoteUp.notice`的子权限了，本来应该发往其他玩家身上的消息全都发到了你身上 XD。
我刚刚编辑了一下 **v1.4.3-VU** 的更新，现在在那里下载的 v1.4.3 的版本应该就能修复这两个问题。

**Comment by BillZhucn** [comment]
那我要让玩家可以发autocast 白名单中指令的投票，是不是给**voteup.user**和**voteup.create.***就行了？

**Comment by Polar-Pumpkin** [comment]
嗯，差不多

**Comment by BillZhucn** [comment]
是我没删之前的cache

**Comment by Polar-Pumpkin** [comment]
哎呀，通过这次报错我也发现了代码的一处隐患啦。
我会再次编辑一下 **v1.4.3-VU** 的更新的

**Comment by BillZhucn** [comment]
但是我好像还是不行（？）

**Comment by BillZhucn** [comment]
```
> lp user 0wbillw0 permission check voteup.create.*
[16:18:03 INFO]: [LP] 0wbillw0 has permission voteup.create.* set to undefined in context global.
> lp user 0wbillw0 permission check voteup.user
[16:18:07 INFO]: [LP] 0wbillw0 has permission voteup.user set to undefined in context global.
```

但是我现在是投票里啥都不能编辑的

**Comment by Polar-Pumpkin** [comment]
会提示啥啊

**Comment by Polar-Pumpkin** [comment]
> 您没有权限这么做. 使用 `/vote create back` 可以返回投票草稿.

这样的吗

**Comment by BillZhucn** [comment]
不是，是进入GUI，然后点击一项修改的时候，提示
>权限验证失败，您不具有修改目标投票内容的权限

**Comment by Polar-Pumpkin** [comment]
![](https://camo.githubusercontent.com/b3518032ca098408de22ec741081fea6bca4bf7a/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30322f32382f3574534a447962545833666d76704c2e6a7067)
- - -
对此造成的不便我深表歉意
- - -
我犯了一个很低级的错误，一个应该用`&&`的地方我写了`||`但是以前能用的不知道为什么现在才出现问题，你很早就给玩家`VoteUp.admin`权限了吗？
已经更新到 **v1.4.3-VU** 里面了

**Comment by BillZhucn** [comment]
之前人少23333333333
现在人多他们想玩Vote，然后发现出问题了2333333，修正了就好
