### ISSUE TITLE
重投问题，重新投票有效，且报错

### ISSUE THREAD

**Issue by MSCMDD** [Polar-Pumpkin/Shoal#11]
```
12:45:46 ERROR]: Could not pass event PlayerJoinEvent to VoteUp v2.0.5-BETA
java.util.ConcurrentModificationException: null
	at java.util.HashMap.forEach(HashMap.java:1432) ~[?:?]
	at net.shoal.sir.voteup.config.CacheManager.lambda$report$5(CacheManager.java:86) ~[VoteUp-2.0.5-BETA.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
	at net.shoal.sir.voteup.config.CacheManager.report(CacheManager.java:85) ~[VoteUp-2.0.5-BETA.jar:?]
	at net.shoal.sir.voteup.listener.PlayerJoinListener.onJoin(PlayerJoinListener.java:61) ~[VoteUp-2.0.5-BETA.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor7.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-238]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-238]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-238]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:325) ~[paper-1.20.2.jar:git-Paper-238]
	at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:130) ~[paper-1.20.2.jar:git-Paper-238]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:18) ~[paper-1.20.2.jar:git-Paper-238]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9) ~[paper-1.20.2.jar:git-Paper-238]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-238]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-238]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-238]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-238]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-238]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-238]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-238]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-238]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[12:45:46 INFO]: AoMe joined the game
[12:45:46 INFO]: AoMe[/127.0.0.1:13499] logged in with entity id 3661 at ([world]29.14331783040025, 65.0, 94.47712955055734)
[12:45:52 INFO]: AoMe issued server command: /vote view 00c357be-9c86-4521-bb27-9817726c7242
[12:45:56 INFO]: AoMe lost connection: Disconnected
[12:45:56 INFO]: AoMe left the game
[12:45:58 INFO]: UUID of player AoMe is b65076b5-f062-3000-87c3-c70d6339a3c4
[12:45:58 ERROR]: Could not pass event PlayerJoinEvent to VoteUp v2.0.5-BETA
java.util.ConcurrentModificationException: null
	at java.util.HashMap.forEach(HashMap.java:1432) ~[?:?]
	at net.shoal.sir.voteup.config.CacheManager.lambda$report$5(CacheManager.java:86) ~[VoteUp-2.0.5-BETA.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
	at net.shoal.sir.voteup.config.CacheManager.report(CacheManager.java:85) ~[VoteUp-2.0.5-BETA.jar:?]
	at net.shoal.sir.voteup.listener.PlayerJoinListener.onJoin(PlayerJoinListener.java:61) ~[VoteUp-2.0.5-BETA.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor7.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-238]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-238]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-238]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:325) ~[paper-1.20.2.jar:git-Paper-238]
	at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:130) ~[paper-1.20.2.jar:git-Paper-238]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:18) ~[paper-1.20.2.jar:git-Paper-238]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9) ~[paper-1.20.2.jar:git-Paper-238]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-238]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-238]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-238]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-238]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-238]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-238]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-238]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-238]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[12:45:58 INFO]: AoMe joined the game
[12:45:58 INFO]: AoMe[/127.0.0.1:13514] logged in with entity id 3691 at ([world]29.14331783040025, 65.0, 94.47712955055734)
[12:46:03 INFO]: AoMe issued server command: /vote view 00c357be-9c86-4521-bb27-9817726c7242
[12:46:11 INFO]: AoMe issued server command: /vote view 00c357be-9c86-4521-bb27-9817726c7242
```

**Comment by Polar-Pumpkin** [comment]
好的，如果我有时间我会赶快修复一下的

**Comment by MSCMDD** [comment]
emmmm重投问题是这样触发的，不关闭服务器和没有执行vote reload的情况下，可以通过退出游戏重新进入游戏再次投票

**Comment by MSCMDD** [comment]
玩家列表此时会显示多个玩家，用户名相同，头颅相同，但VoteUp\Votes的用户列表正常

**Comment by MSCMDD** [comment]
另外希望更新下ParrotX轮子
AwA

**Comment by Polar-Pumpkin** [comment]
> 另外希望更新下ParrotX轮子 AwA

是指为 VoteUp 更新到最新版的 ParrotX 版本吗？

**Comment by MSCMDD** [comment]
嗯
