### ISSUE TITLE
bug:voteup2崩溃

### ISSUE THREAD

**Issue by roughanddai** [Polar-Pumpkin/Shoal#4]
输入/vote create 崩溃，核心akarin #33 1.15.2  
旧版文件未删除
`[20:56:46] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'vote' in plugin VoteUp v2.0-BETA
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Akarin-"39eaaef"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Akarin-"39eaaef"]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:760) ~[patched_1.15.2.jar:git-Akarin-"39eaaef"]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1852) ~[patched_1.15.2.jar:git-Akarin-"39eaaef"]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1660) ~[patched_1.15.2.jar:git-Akarin-"39eaaef"]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Akarin-"39eaaef"]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Akarin-"39eaaef"]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Akarin-"39eaaef"]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Akarin-"39eaaef"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Akarin-"39eaaef"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Akarin-"39eaaef"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Akarin-"39eaaef"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1093) ~[patched_1.15.2.jar:git-Akarin-"39eaaef"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1086) ~[patched_1.15.2.jar:git-Akarin-"39eaaef"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Akarin-"39eaaef"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1223) ~[patched_1.15.2.jar:git-Akarin-"39eaaef"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:958) ~[patched_1.15.2.jar:git-Akarin-"39eaaef"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.IllegalArgumentException: Size for custom inventory must be a multiple of 9 between 9 and 54 slots (got 0)
	at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.15.2.jar:git-Akarin-"39eaaef"]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.createInventory(CraftServer.java:1677) ~[patched_1.15.2.jar:git-Akarin-"39eaaef"]
	at org.bukkit.Bukkit.createInventory(Bukkit.java:1107) ~[patched_1.15.2.jar:git-Akarin-"39eaaef"]
	at net.shoal.sir.voteup.data.inventory.CreateInventoryHolder.construct(CreateInventoryHolder.java:52) ~[?:?]
	at net.shoal.sir.voteup.data.inventory.CreateInventoryHolder.<init>(CreateInventoryHolder.java:44) ~[?:?]
	at net.shoal.sir.voteup.command.subcommands.CreateCmd.execute(CreateCmd.java:64) ~[?:?]
	at org.serverct.parrot.parrotx.command.CommandHandler.onCommand(CommandHandler.java:53) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Akarin-"39eaaef"]
	... 17 more`

**Comment by Polar-Pumpkin** [comment]
很抱歉现在才看到这个 Issue。
不知道你有没有开邮件提醒啥的，或者看 Github 频不频繁。

咳咳，说多了。这个问题很好解决，是 1.14 之后无法创建没有格子的 Gui(Inventory) 的问题，为什么要创建这样的 Gui 呢，因为插件读不到正确的 Gui 配置文件。
因为重新设计了每个 Gui，所以配置文件结构差异还是很大的，如果没有改动之前的 Gui 配置文件的内容的话，可以直接删掉 Guis 文件夹重新生成一下。

这算是一个遗留问题，在发布前我已经意识到这个问题了的，但是忘记改了，在下一个版本会修好的，在无法读取到正确的 Gui 配置文件的时候生成一个空的 Gui 提醒你（而不是生成一个错误233）。不过一般不乱改 Gui 配置文件改到了 Yaml “键名”，插件生成的 Gui 配置文件都是能读到的，旧版本结构不一样，键名也不一样。

**Comment by roughanddai** [comment]
> 很抱歉现在才看到这个 Issue。
> 不知道你有没有开邮件提醒啥的，或者看 Github 频不频繁。
> 
> 咳咳，说多了。这个问题很好解决，是 1.14 之后无法创建没有格子的 Gui(Inventory) 的问题，为什么要创建这样的 Gui 呢，因为插件读不到正确的 Gui 配置文件。
> 因为重新设计了每个 Gui，所以配置文件结构差异还是很大的，如果没有改动之前的 Gui 配置文件的内容的话，可以直接删掉 Guis 文件夹重新生成一下。
> 
> 这算是一个遗留问题，在发布前我已经意识到这个问题了的，但是忘记改了，在下一个版本会修好的，在无法读取到正确的 Gui 配置文件的时候生成一个空的 Gui 提醒你（而不是生成一个错误233）。不过一般不乱改 Gui 配置文件改到了 Yaml “键名”，插件生成的 Gui 配置文件都是能读到的，旧版本结构不一样，键名也不一样。

上学，所以只能间歇性看issues
